import { Check, Zap, Sparkles, Users } from "lucide-react";

export const plans = [
  {
    id: "essai",
    name: "Essai",
    price: "gratuit",
    quota: 4500,
    description: "Découvrez Inboria gratuitement — mode équipe inclus",
    features: [
      "4 500 crédits IA offerts (usage unique, sans carte bancaire)",
      "Tri & priorisation automatiques de votre boîte de réception",
      "Brouillons & réponses générés par Inboria",
      "3 rubriques personnalisées",
      "Connexion Gmail, Outlook ou IMAP",
      "Essai en équipe : invitez jusqu'à 3 collègues",
      "Testez les fonctions Business : boîtes partagées, assignation, commentaires internes",
      "Applications web & mobile",
      "Support par email",
    ],
    icon: Check,
  },
  {
    id: "solo",
    name: "Solo",
    price: "9",
    quota: 3000,
    description: "Pour les indépendants",
    features: [
      "3 000 crédits IA / mois",
      "Rubriques illimitées",
      "Brief quotidien",
      "Brouillons IA proactifs",
      "Extraction automatique des tâches",
      "Support prioritaire",
      "Dépassement : 0,002€ / crédit",
    ],
    icon: Zap,
  },
  {
    id: "pro",
    name: "Pro",
    price: "21.99",
    priceYear: "211.10",
    quota: 10000,
    description: "Idéal pour les professionnels",
    features: [
      "10 000 crédits IA / mois",
      "Rubriques illimitées",
      "Brief quotidien",
      "Brouillons IA proactifs",
      "Extraction automatique des tâches",
      "Statistiques détaillées",
      "Support prioritaire",
      "Dépassement : 0,001€ / crédit",
    ],
    icon: Sparkles,
  },
  {
    id: "business",
    name: "Business",
    price: "16.99",
    priceYear: "163.10",
    quota: 10000,
    description: "Pour les équipes",
    features: [
      "10 000 crédits IA / siège / mois",
      "Tout du plan Pro inclus",
      "Minimum 3 sièges, jusqu'à 50",
      "Boîtes partagées entre collègues",
      "Assignation de tâches entre membres",
      "API dédiée",
      "Support prioritaire",
      "Dépassement : 0,001€ / crédit",
    ],
    icon: Users,
    hasSeats: true,
  },
] as const;

export type PlanId = (typeof plans)[number]["id"];
