import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import profileRouter from "./profile";
import emailsRouter from "./emails";
import categoriesRouter from "./categories";
import tasksRouter from "./tasks";
import dashboardRouter from "./dashboard";
import bootstrapRouter from "./bootstrap";
import aiRouter from "./ai";
import emailConnectRouter from "./email-connect";
import webhookRouter from "./webhook";
import projectsRouter from "./projects";
import paddleRouter from "./paddle";
import integrationsRouter from "./integrations";
import organisationsRouter from "./organisations";
import sharedMailboxesRouter from "./shared-mailboxes";
import commentsRouter from "./comments";
import assignmentsRouter from "./assignments";
import notificationsRouter from "./notifications";
import teamDashboardRouter from "./team-dashboard";
import followupsRouter from "./followups";
import exportRouter from "./export";
import attachmentsRouter from "./attachments";
import appointmentsRouter from "./appointments";
import waitlistRouter from "./waitlist";
import adminRouter from "./admin";
import renderFailuresRouter from "./render-failures";
import blockedSendersRouter from "./blocked-senders";
import autopilotRouter from "./autopilot";
import inboriaContextRouter from "./inboria-context";
import inboriaExpertRouter from "./inboria-expert";
import templatesRouter from "./templates";
import automationRulesRouter from "./automation-rules";
import slaRouter from "./sla";
import apiKeysRouter from "./api-keys";
import webhooksMgmtRouter from "./webhooks-mgmt";
import analyticsRouter from "./analytics";
import publicApiRouter from "./public-api";
import teamAccessLogRouter from "./team-access-log";
import contactsRouter from "./contacts";
import calendarRouter from "./calendar";
import foldersRouter from "./folders";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(assignmentsRouter);
router.use(emailsRouter);
router.use(categoriesRouter);
router.use(tasksRouter);
router.use(dashboardRouter);
router.use(bootstrapRouter);
router.use(aiRouter);
router.use(emailConnectRouter);
router.use(webhookRouter);
router.use(projectsRouter);
router.use(paddleRouter);
router.use(integrationsRouter);
router.use(organisationsRouter);
router.use(sharedMailboxesRouter);
router.use(commentsRouter);
router.use(notificationsRouter);
router.use(teamDashboardRouter);
router.use(followupsRouter);
router.use(exportRouter);
router.use(attachmentsRouter);
router.use(appointmentsRouter);
router.use(waitlistRouter);
router.use(adminRouter);
router.use(renderFailuresRouter);
router.use(blockedSendersRouter);
router.use(autopilotRouter);
router.use(inboriaContextRouter);
router.use(inboriaExpertRouter);
router.use(templatesRouter);
router.use(automationRulesRouter);
router.use(slaRouter);
router.use(apiKeysRouter);
router.use(webhooksMgmtRouter);
router.use(analyticsRouter);
router.use(publicApiRouter);
router.use(teamAccessLogRouter);
router.use(contactsRouter);
router.use(calendarRouter);
router.use(foldersRouter);

export default router;
