import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import profileRouter from "./profile";
import emailsRouter from "./emails";
import categoriesRouter from "./categories";
import tasksRouter from "./tasks";
import dashboardRouter from "./dashboard";
import aiRouter from "./ai";
import emailConnectRouter from "./email-connect";
import webhookRouter from "./webhook";
import projectsRouter from "./projects";
import paddleRouter from "./paddle";
import integrationsRouter from "./integrations";
import organisationsRouter from "./organisations";
import sharedMailboxesRouter from "./shared-mailboxes";
import commentsRouter from "./comments";
import assignmentsRouter from "./assignments";
import notificationsRouter from "./notifications";
import teamDashboardRouter from "./team-dashboard";
import followupsRouter from "./followups";
import exportRouter from "./export";
import attachmentsRouter from "./attachments";
import appointmentsRouter from "./appointments";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(assignmentsRouter);
router.use(emailsRouter);
router.use(categoriesRouter);
router.use(tasksRouter);
router.use(dashboardRouter);
router.use(aiRouter);
router.use(emailConnectRouter);
router.use(webhookRouter);
router.use(projectsRouter);
router.use(paddleRouter);
router.use(integrationsRouter);
router.use(organisationsRouter);
router.use(sharedMailboxesRouter);
router.use(commentsRouter);
router.use(notificationsRouter);
router.use(teamDashboardRouter);
router.use(followupsRouter);
router.use(exportRouter);
router.use(attachmentsRouter);
router.use(appointmentsRouter);

export default router;
