DROP POLICY IF EXISTS "shared_mailbox_select" ON public.shared_mailboxes;
DROP POLICY IF EXISTS "shared_mailbox_insert_admin" ON public.shared_mailboxes;
DROP POLICY IF EXISTS "shared_mailbox_delete_admin" ON public.shared_mailboxes;
DROP POLICY IF EXISTS "shared_mailbox_members_select" ON public.shared_mailbox_members;
DROP POLICY IF EXISTS "shared_mailbox_members_insert_admin" ON public.shared_mailbox_members;
DROP POLICY IF EXISTS "shared_mailbox_members_delete_admin" ON public.shared_mailbox_members;
DROP INDEX IF EXISTS idx_shared_mailbox_org;
DROP INDEX IF EXISTS idx_shared_mailbox_members_mailbox;
DROP INDEX IF EXISTS idx_shared_mailbox_members_user;
DROP INDEX IF EXISTS idx_emails_shared_mailbox;
DROP INDEX IF EXISTS idx_emails_claimed_by;
DROP TABLE IF EXISTS public.shared_mailbox_members;
DROP TABLE IF EXISTS public.shared_mailboxes;
ALTER TABLE public.emails DROP COLUMN IF EXISTS shared_mailbox_id;
ALTER TABLE public.emails DROP COLUMN IF EXISTS claimed_by;
ALTER TABLE public.emails DROP COLUMN IF EXISTS claimed_at;
CREATE TABLE public.shared_mailboxes (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, organisation_id uuid NOT NULL REFERENCES public.organisations(id) ON DELETE CASCADE, name text NOT NULL, email_address text NOT NULL, connection_id uuid REFERENCES public.email_connections(id) ON DELETE SET NULL, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now());
ALTER TABLE public.shared_mailboxes ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.shared_mailbox_members (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, shared_mailbox_id uuid NOT NULL REFERENCES public.shared_mailboxes(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, can_reply boolean DEFAULT true, added_at timestamptz DEFAULT now(), UNIQUE(shared_mailbox_id, user_id));
ALTER TABLE public.shared_mailbox_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emails ADD COLUMN shared_mailbox_id uuid REFERENCES public.shared_mailboxes(id) ON DELETE SET NULL;
ALTER TABLE public.emails ADD COLUMN claimed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.emails ADD COLUMN claimed_at timestamptz;
CREATE POLICY "shared_mailbox_select" ON public.shared_mailboxes FOR SELECT USING (organisation_id IN (SELECT om.organisation_id FROM public.organisation_members AS om WHERE om.user_id = auth.uid()));
CREATE POLICY "shared_mailbox_insert_admin" ON public.shared_mailboxes FOR INSERT WITH CHECK (organisation_id IN (SELECT om.organisation_id FROM public.organisation_members AS om WHERE om.user_id = auth.uid() AND om.role = 'admin'));
CREATE POLICY "shared_mailbox_delete_admin" ON public.shared_mailboxes FOR DELETE USING (organisation_id IN (SELECT om.organisation_id FROM public.organisation_members AS om WHERE om.user_id = auth.uid() AND om.role = 'admin'));
CREATE POLICY "shared_mailbox_members_select" ON public.shared_mailbox_members FOR SELECT USING (shared_mailbox_id IN (SELECT sm.id FROM public.shared_mailboxes AS sm WHERE sm.organisation_id IN (SELECT om.organisation_id FROM public.organisation_members AS om WHERE om.user_id = auth.uid())));
CREATE POLICY "shared_mailbox_members_insert_admin" ON public.shared_mailbox_members FOR INSERT WITH CHECK (shared_mailbox_id IN (SELECT sm.id FROM public.shared_mailboxes AS sm WHERE sm.organisation_id IN (SELECT om.organisation_id FROM public.organisation_members AS om WHERE om.user_id = auth.uid() AND om.role = 'admin')));
CREATE POLICY "shared_mailbox_members_delete_admin" ON public.shared_mailbox_members FOR DELETE USING (shared_mailbox_id IN (SELECT sm.id FROM public.shared_mailboxes AS sm WHERE sm.organisation_id IN (SELECT om.organisation_id FROM public.organisation_members AS om WHERE om.user_id = auth.uid() AND om.role = 'admin')));
CREATE INDEX idx_shared_mailbox_org ON public.shared_mailboxes(organisation_id);
CREATE INDEX idx_shared_mailbox_members_mailbox ON public.shared_mailbox_members(shared_mailbox_id);
CREATE INDEX idx_shared_mailbox_members_user ON public.shared_mailbox_members(user_id);
CREATE INDEX idx_emails_shared_mailbox ON public.emails(shared_mailbox_id);
CREATE INDEX idx_emails_claimed_by ON public.emails(claimed_by);
