kind = "web"
previewPath = "/"
title = "NCV Mail"
version = "1.0.0"
id = "artifacts/ncv-mail"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25212

[services.development]
run = "pnpm --filter @workspace/ncv-mail run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ncv-mail", "run", "build" ]
publicDir = "artifacts/ncv-mail/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25212"
BASE_PATH = "/"
